apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmedge
handler: wasmedge
---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: order-demo-wasi
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/clubanderson/order-demo-wasi:latest
        name: order-demo-wasi
        env:
        - name: DATABASE_URL
          value: "mysql://user:passwd@mysql.mysql.svc.cluster.local:3306/mysql"
        resources: {}
      restartPolicy: Never
      runtimeClassName: wasmedge
  backoffLimit: 1
